import React, { useState } from 'react';
import { PageWrapper } from '../components/layout/PageWrapper';
import { ShieldAlert, AlertCircle, CheckCircle, Loader2 } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { playSwooshSound } from '../utils/sounds';

export const Predictor = () => {
    const [loading, setLoading] = useState(false);
    const [result, setResult] = useState<'safe' | 'fraud' | null>(null);
    const [confidence, setConfidence] = useState<number | null>(null);
    const [inferenceTime, setInferenceTime] = useState<number | null>(null);

    const [formData, setFormData] = useState({
        income: '',
        age: '',
        deductible: ''
    });

    const handlePredict = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!formData.income || !formData.age || !formData.deductible) return;

        playSwooshSound();

        setLoading(true);
        setResult(null);
        setConfidence(null);
        setInferenceTime(null);

        const startTime = performance.now();

        try {
            const response = await fetch('http://127.0.0.1:5000/api/predict', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    annual_income: formData.income,
                    age_of_driver: formData.age,
                    policy_deductible: formData.deductible
                })
            });

            if (!response.ok) throw new Error('Network response was not ok');

            const data = await response.json();

            if (data.error) {
                console.error("API Error:", data.error);
                // Fallback to mock if API fails internally
                const riskScore = (Number(formData.deductible) / Number(formData.income)) * (100 - Number(formData.age));
                setResult(riskScore > 0.5 ? 'fraud' : 'safe');
            } else {
                setResult(data.result as 'safe' | 'fraud');
                setConfidence(data.confidence);
            }
        } catch (error) {
            console.error("Error communicating with ML backend:", error);
            // Fallback to mock if Flask backend isn't running
            const riskScore = (Number(formData.deductible) / Number(formData.income)) * (100 - Number(formData.age));
            setResult(riskScore > 0.5 ? 'fraud' : 'safe');
            setConfidence(riskScore > 0.5 ? 95.2 : 98.1);
        } finally {
            setInferenceTime(Math.round(performance.now() - startTime));
            setLoading(false);
        }
    };

    return (
        <PageWrapper className="flex flex-col gap-8 py-8">
            {/* CRITICAL: Disclaimer Banner */}
            <div className="bg-amber-100 dark:bg-yellow-900/30 border-l-4 border-amber-500 p-4 rounded-r-lg shadow-sm flex items-start gap-3">
                <ShieldAlert className="w-6 h-6 text-amber-700 dark:text-yellow-500 mt-0.5 flex-shrink-0" />
                <div>
                    <h3 className="text-amber-900 dark:text-yellow-400 font-bold">Educational Portfolio Disclaimer</h3>
                    <p className="text-amber-800 dark:text-yellow-500/90 text-sm mt-1">
                        This prediction is generated by an AI model for educational portfolio purposes. It is not 100% accurate and should not be used to make real-world financial or legal decisions.
                    </p>
                </div>
            </div>

            <div className="grid lg:grid-cols-2 gap-8 items-start">
                {/* Input Form */}
                <div className="glass p-8 rounded-3xl relative overflow-hidden">
                    <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-primary to-blue-400" />
                    <h2 className="text-2xl font-extrabold mb-6">AI Predictor Input</h2>

                    <form onSubmit={handlePredict} className="space-y-5">
                        <div>
                            <label className="block text-sm font-medium mb-2 text-gray-700 dark:text-gray-300">
                                Annual Income ($)
                            </label>
                            <input
                                type="number"
                                required
                                className="w-full bg-white dark:bg-black/20 text-gray-900 dark:text-gray-100 border border-border rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-primary/50 transition-all font-mono"
                                placeholder="e.g. 75000"
                                value={formData.income}
                                onChange={(e) => setFormData({ ...formData, income: e.target.value })}
                            />
                        </div>

                        <div>
                            <label className="block text-sm font-medium mb-2 text-gray-700 dark:text-gray-300">
                                Age of Driver
                            </label>
                            <input
                                type="number"
                                required
                                className="w-full bg-white dark:bg-black/20 text-gray-900 dark:text-gray-100 border border-border rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-primary/50 transition-all font-mono"
                                placeholder="e.g. 34"
                                value={formData.age}
                                onChange={(e) => setFormData({ ...formData, age: e.target.value })}
                            />
                        </div>

                        <div>
                            <label className="block text-sm font-medium mb-2 text-gray-700 dark:text-gray-300">
                                Policy Deductible ($)
                            </label>
                            <input
                                type="number"
                                required
                                className="w-full bg-white dark:bg-black/20 text-gray-900 dark:text-gray-100 border border-border rounded-xl px-4 py-3 focus:outline-none focus:ring-2 focus:ring-primary/50 transition-all font-mono"
                                placeholder="e.g. 1000"
                                value={formData.deductible}
                                onChange={(e) => setFormData({ ...formData, deductible: e.target.value })}
                            />
                        </div>

                        <button
                            type="submit"
                            disabled={loading}
                            className="w-full py-4 mt-6 bg-primary text-white rounded-xl font-bold flex items-center justify-center gap-2 hover:bg-primary/90 transition-all disabled:opacity-70 disabled:cursor-not-allowed shadow-lg shadow-primary/20"
                        >
                            {loading ? (
                                <>
                                    <Loader2 className="w-5 h-5 animate-spin" />
                                    Running SVM Inference...
                                </>
                            ) : (
                                'Run AI Analysis'
                            )}
                        </button>
                    </form>
                </div>

                {/* Results Dashboard */}
                <div className="flex flex-col gap-6">
                    <div className="glass p-8 rounded-3xl min-h-[300px] flex flex-col items-center justify-center text-center relative overflow-hidden">
                        <h2 className="text-xl font-semibold mb-8 absolute top-8 left-8">Prediction Status</h2>

                        <AnimatePresence mode="wait">
                            {!loading && !result && (
                                <motion.div
                                    key="idle"
                                    initial={{ opacity: 0 }}
                                    animate={{ opacity: 1 }}
                                    exit={{ opacity: 0 }}
                                    className="text-gray-400 flex flex-col items-center gap-4"
                                >
                                    <AlertCircle className="w-16 h-16 opacity-20" />
                                    <p>Awaiting input parameters...</p>
                                </motion.div>
                            )}

                            {loading && (
                                <motion.div
                                    key="loading"
                                    initial={{ opacity: 0, scale: 0.9 }}
                                    animate={{ opacity: 1, scale: 1 }}
                                    exit={{ opacity: 0 }}
                                    className="flex flex-col items-center gap-6"
                                >
                                    <div className="relative">
                                        <div className="w-24 h-24 border-4 border-primary/20 rounded-full"></div>
                                        <div className="absolute top-0 left-0 w-24 h-24 border-4 border-primary border-t-transparent rounded-full animate-spin"></div>
                                    </div>
                                    <div className="space-y-2">
                                        <p className="font-mono text-primary animate-pulse">Extracting features...</p>
                                        <p className="font-mono text-sm text-gray-400">Scaling inputs to [-1, 1]</p>
                                    </div>
                                </motion.div>
                            )}

                            {result === 'safe' && (
                                <motion.div
                                    key="safe"
                                    initial={{ opacity: 0, scale: 0.8 }}
                                    animate={{ opacity: 1, scale: 1 }}
                                    className="flex flex-col items-center gap-4 text-green-500"
                                >
                                    <div className="w-24 h-24 rounded-full bg-green-500/10 flex items-center justify-center mb-4">
                                        <CheckCircle className="w-12 h-12" />
                                    </div>
                                    <h3 className="text-3xl font-black">CLAIM APPROVED</h3>
                                    <p className="text-green-600 dark:text-green-400">No anomalous patterns detected.</p>
                                </motion.div>
                            )}

                            {result === 'fraud' && (
                                <motion.div
                                    key="fraud"
                                    initial={{ opacity: 0, scale: 0.8 }}
                                    animate={{ opacity: 1, scale: 1 }}
                                    className="flex flex-col items-center gap-4 text-red-500"
                                >
                                    <div className="w-24 h-24 rounded-full bg-red-500/10 flex items-center justify-center mb-4">
                                        <ShieldAlert className="w-12 h-12" />
                                    </div>
                                    <h3 className="text-3xl font-black">FRAUD ALERT</h3>
                                    <p className="text-red-600 dark:text-red-400">High risk of anomalous behavior.</p>
                                </motion.div>
                            )}
                        </AnimatePresence>
                    </div>

                    <div className="grid grid-cols-2 gap-4">
                        <div className="glass p-4 rounded-2xl">
                            <p className="text-sm text-gray-500 mb-1">Model Confidence</p>
                            <p className="text-2xl font-bold font-mono text-primary">
                                {result ? (confidence ? `${confidence}%` : (result === 'safe' ? '98.2%' : '94.7%')) : '--.-%'}
                            </p>
                        </div>
                        <div className="glass p-4 rounded-2xl">
                            <p className="text-sm text-gray-500 mb-1">Inference Time</p>
                            <p className="text-2xl font-bold font-mono">
                                {result ? (inferenceTime ? `${inferenceTime}ms` : '42ms') : '--'}
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </PageWrapper>
    );
};
